link:
  home: "http://www.railstutorial.org/"
  news: "https://news.railstutorial.org/"
  author: "https://www.michaelhartl.com/"
  help:
    book: "https://www.railstutorial.org/book"
    default: "https://www.railstutorial.org/help"
  about:
    screencasts: "https://screencasts.railstutorial.org/"
    book: "https://www.railstutorial.org/book"
    learnenough: "https://www.learnenough.com/"
    home: "https://www.railstutorial.org/"
  contact:
    contact: "https://www.railstutorial.org/contact"
validations:
  user:
    email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
    max_name_length: 50
    max_email_length: 255
    min_password_length: 6
    avatar_size: 50
helper:
  user:
    size: 80
form:
  check_box: "1"
pagination:
  per_page: 10
time:
  expried: 2
